In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=['the glass of water',
      'the glass of juice',
      'the cup of tea',
      'I am a good student',
      'I am a good developer',
      'I understand the meaning of embedding',
      'Your classes are good']

In [3]:
sent

['the glass of water',
 'the glass of juice',
 'the cup of tea',
 'I am a good student',
 'I am a good developer',
 'I understand the meaning of embedding',
 'Your classes are good']

In [4]:
### Vocabulary size
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[8022, 9561, 9445, 1340], [8022, 9561, 9445, 8080], [8022, 7616, 9445, 4214], [153, 8187, 9306, 9732, 6090], [153, 8187, 9306, 9732, 7688], [153, 390, 8022, 1079, 9445, 2629], [4336, 1492, 8647, 9732]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8022 9561 9445 1340]
 [   0    0    0    0 8022 9561 9445 8080]
 [   0    0    0    0 8022 7616 9445 4214]
 [   0    0    0  153 8187 9306 9732 6090]
 [   0    0    0  153 8187 9306 9732 7688]
 [   0    0  153  390 8022 1079 9445 2629]
 [   0    0    0    0 4336 1492 8647 9732]]


In [8]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 75ms/step
[[[ 0.03993108  0.01175923  0.04271821  0.03244288 -0.01505361
    0.03555622 -0.01517053 -0.0396102   0.04169673  0.0254408 ]
  [ 0.03993108  0.01175923  0.04271821  0.03244288 -0.01505361
    0.03555622 -0.01517053 -0.0396102   0.04169673  0.0254408 ]
  [ 0.03993108  0.01175923  0.04271821  0.03244288 -0.01505361
    0.03555622 -0.01517053 -0.0396102   0.04169673  0.0254408 ]
  [ 0.03993108  0.01175923  0.04271821  0.03244288 -0.01505361
    0.03555622 -0.01517053 -0.0396102   0.04169673  0.0254408 ]
  [-0.03136734  0.00133143  0.02646023  0.04674863 -0.03820299
    0.00265099 -0.00197612  0.0107258  -0.03520332  0.03013525]
  [-0.02029202  0.00042603 -0.02075167  0.00550709  0.00860423
   -0.01674325 -0.04737566 -0.04137176 -0.01251853  0.01636355]
  [-0.00265779  0.00695177  0.04697747 -0.00914318 -0.01032539
    0.00488025  0.00172325 -0.04707931 -0.03915906  0.02247962]
  [ 0.00771992  0.03540574 -0.00191142 -0.01720925  0.03631

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 3266, 1865,  204, 2270], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 18ms/step
[[ 0.04868168 -0.03847203 -0.00724984  0.0120919   0.0092644   0.01915926
  -0.02589082  0.035042   -0.00451585  0.01324726]
 [ 0.04868168 -0.03847203 -0.00724984  0.0120919   0.0092644   0.01915926
  -0.02589082  0.035042   -0.00451585  0.01324726]
 [ 0.04868168 -0.03847203 -0.00724984  0.0120919   0.0092644   0.01915926
  -0.02589082  0.035042   -0.00451585  0.01324726]
 [ 0.04868168 -0.03847203 -0.00724984  0.0120919   0.0092644   0.01915926
  -0.02589082  0.035042   -0.00451585  0.01324726]
 [-0.01580056 -0.03421537  0.00350169  0.00837114 -0.02277646 -0.02136178
  -0.02409724  0.04546063  0.02826094  0.02342044]
 [ 0.01089367 -0.0278523  -0.02267233 -0.00885255 -0.0286623   0.0086977
   0.00735921 -0.03254628 -0.00545728  0.0475697 ]
 [-0.02994357  0.04612741  0.01199242 -0.02783521 -0.0298906  -0.03164034
   0.02576547 -0.04239463 -0.001909   -0.04754017]
 [ 0.04152414  0.00224151 -0.04446933  0.01504637 -0.0038555   0.04200891
